config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :twits
  resources :users
  resources :friendships
  get 'user_dashboard', to: "users#user_dashboard"
  get 'my_followers', to: 'users#my_followers'
  get 'user_twits', to: "twits#user_twits"
  get 'search_followers', to: "users#search"
  post 'add_follower', to: 'users#add_follower'
  get '/twits/hashtag/:name', to:'twits#hashtags'
  root "users#user_dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
    belongs_to :user
    belongs_to :follower, class_name: 'User' 
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :twit_tags
    has_many :twits, through: :twit_tags
end

app/models/twit.rb
class Twit < ApplicationRecord
    belongs_to :user #create a method to go from tweet to user
    validates :message, presence:true, length: { maximum:120 }
    has_many :twit_tags
    has_many :tags, through: :twit_tags

    after_create do
        twit = Twit.find_by(id: self.id)
        hashtags = self.message.scan(/#\w+/)
        hashtags.uniq.map do |hashtag|
            tag = Tag.find_or_create_by(message_tag: hashtag.downcase.delete('#'))
            twit.tags << tag
        end
    end

    before_update do
        twit = Twit.find_by(id: self.id)
        twit.tags.clear
        hashtags = self.message.scan(/#\w+/)
        hashtags.uniq.map do |hashtag|
            tag = Tag.find_or_create_by(message_tag: hashtag.downcase.delete('#'))
            twit.tags << tag
        end
    end
end

app/models/twit_tag.rb
class TwitTag < ApplicationRecord
    belongs_to :twit
    belongs_to :tag 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :twits
  has_many :friendships
  has_many :followers, through: :friendships

  has_attached_file :image, styles: { medium: "300x300>", thumb: "50x50>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def not_followers_with?(follower_id)
    friendships.where(follower_id: follower_id).count < 1
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def self.username_matches(param)
    matches('username', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.search(param)
    return User.none if param.blank?

    param.strip!
    param.downcase!
    (username_matches(param) + email_matches(param)).uniq
  end

  def self.matches(field_name, param)
    where("lower(#{field_name}) like ?", "%#{param}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def destroy
    @follower = User.find(params[:id])
    @friendship = current_user.friendships.where(follower_id: params[:id]).first
    @friendship.destroy
    redirect_to user_path(@follower.id)
  end
end

app/controllers/twits_controller.rb
class TwitsController < ApplicationController
    def show
        @user = User.find(params[:id])
        @twit = Twit.find(params[:id])
    end

    def create
        @twit = current_user.twits.new(twits_params)
        @twit.save
        respond_to do |format|
          format.html { redirect_to user_twits_path }
          format.json { }
        end

    end

    def edit
        @twit = Twit.find(params[:id])
    end

    def update
      @twit = Twit.find(params[:id])
      @twit.update(twits_params)
      redirect_to user_twits_path
    end

    def destroy
      @twit = Twit.find(params[:id])
      @twit.destroy
      redirect_to user_twits_path
    end

    def user_twits
        @twits = current_user.twits.all
        @twit = current_user.twits.new
    end

    def hashtags
        tag = Tag.find_by(message_tag: params[:name])
        @twits = tag.twits
    end

    private

    def twits_params
        params.require(:twit).permit(:message, :user_id)
    end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :image])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :image])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
    def user_dashboard
        @twit = current_user.twits.new
    end
    
    def search
        @friendships = current_user.followers
        @users = User.search(params[:search_param])
        
        if @users
            @users = current_user.except_current_user(@users)
            render "search"
        else
            render status: :not_found, nothing: true
        end
    end
    
    def my_followers
        @friendships = current_user.followers
    end
    
    def add_follower
        @follower = User.find(params[:follower])
        current_user.friendships.build(follower_id: @follower.id)
        if current_user.save
        redirect_to user_path(@follower.id), notice: "Friend was successfully added"
        else
        redirect_to user_path(@follower.id), flash[:error] = "There was an error with adding user as friend"
        end
    end
    
    def show
        @user = User.find(params[:id])
    end
    
    private
    
    def users_params
        params.require(:user).permit(:username, :email)
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twits_helper.rb
module TwitsHelper
    def render_with_hashtags(message)
        message.gsub(/#\w+/) { |word| link_to word, "/twits/hashtag/#{word.delete('#').downcase}"}.html_safe
    end
end

app/views/common/_spinner.html.erb
<div id="spinner" class="row col-md-12 text-center spinner" style="display: none;">
  <i class="fa fa-spinner fa-spin fa-2x"></i> Processing...
</div>

app/views/layouts/_navigation.html.erb
<% if current_user %>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Home", root_path, class: "navbar-brand" %>
  <%= image_tag current_user.image.url(:thumb) %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "My Tweets",user_twits_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <%= form_tag search_followers_path, method: :get do %>
      <form class="form-inline my-2 my-lg-0">
        <%= text_field_tag :search_param, params[:search_param], placeholder: 'search for a user', autofocus: true %>
        <%= button_tag 'Search', type: 'submit', class: "btn btn-sm btn-success" %>
      </form>
      <% end %>
      <li class="nav-item">
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/twits/_twit_create.html.erb
<h1>Write a new tweet</h1>

<%= form_for @twit do |f| %>
    <p>
        <%= f.label :message %><br/>
        <%= f.text_field :message %>
    </p>
    
    <%= f.submit 'Create tweet' %>
    
<% end %>

app/views/twits/_twits_show.html.erb
<div id ="new-tweet">
<% @twits.each do |twit| %>
        <p><%= render_with_hashtags(twit.message) %></p>
        <p>Created <%= time_ago_in_words(twit.created_at)%> ago on
        <%= twit.updated_at.to_date.to_s + " " + twit.updated_at.strftime("%I:%M%p").to_s %></p>
        <p><%= link_to 'Edit', edit_twit_path(twit) %></p>
        <p><%= link_to 'Delete', twit_path(twit), method: :delete %></p>
<% end %>
</div>

app/views/twits/create.js.erb
$(#new-tweet).html("<%= j render 'twits_show' %>");

app/views/twits/edit.html.erb
<h1>Edit Tweet</h1>

<%= form_for @twit do |f| %>
    <p>
        <%= f.label :message %><br/>
        <%= f.text_field :message %>
    </p>

    <%= f.submit %>

    <% end %>

app/views/twits/hashtags.html.erb
<%= render 'layouts/navigation' %>

<div class ="container text-center">
    <% @twits.each do |twit| %>
        <p><%= twit.user.username %> wrote:</p>
        <p><%= render_with_hashtags(twit.message) %></p>
    <% end %>    
</div>

app/views/twits/show.html.erb
<h1>Feed</h1>

<p><%= @user.username + " wrote a message"%></p>
<p><%= @twit.message %></p>

app/views/twits/user_twits.html.erb
<%= render 'layouts/navigation' %>

<div class ="container text-center">

<p><%= current_user.username %>'s tweets</p>

<div><%= render 'twits/twit_create' %></div>

<div><%= render 'twits/twits_show' %></div>

</div>

app/views/users/search.html.erb
<%= render 'layouts/navigation' %>

<h1>Search results</h1>

<% if @users %>
    <% if @users.size > 0 %>
        <div>
            <table>
                <tbody>
                    <% @users.each do |user| %>
                    <tr>
                        <td><strong>Name:</strong> <%= user.username %></td>
                        <td><strong>Email:</strong> <%= user.email %></td>
                        <td><%= link_to "View Profile", user_path(user), class: "btn btn-xs btn-success" %>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    <% end %>
<% end %>

app/views/users/show.html.erb
<%= render 'layouts/navigation' %>

<div class ="container text-center">
    
<h2>Profile Page of <%= @user.username %></h2>

<% if current_user.id != @user.id %>
    <% if current_user.not_followers_with?(@user.id) %>
        <%= link_to "Follow", add_follower_path(user: current_user, follower: @user), class: "btn btn-xs btn-success", method: :post %>
        <% else %>
        <%= link_to 'Unfollow', friendship_path(@user.id), 
                                method: :delete, class: "btn btn-xs btn-danger" %>
    <% end %>
<% end %>
    
<p><%= @user.username %>'s tweets</p>

<% @user.twits.each do |twit| %>
    <p><%= twit.user.username %> wrote:</p>
    <p><%= render_with_hashtags(twit.message) %></p>
<% end %>

</div>

app/views/users/user_dashboard.html.erb
<%= render 'layouts/navigation' %>

<div class="container text-center">
    <div><%= render 'twits/twit_create' %></div>
    <%= current_user.username %>'s tweeter feed

</div>

app/views/welcome/index.html.erb
<div class="container">

<h1>Welcome to Twitter Clone App</h1>

<%= link_to "Sign out", destroy_user_session_path, method: :delete %>

</div>